const journals = [
	{name: 'Nature Astronomy', colour: '#516B78', logo: './images/Nature-Astronomy.png'},
	{name: 'Nature Biomedical Engineering', colour: '#85237F', logo: './images/Nature-Biomedical-Engineering.png'},
	{name: 'Nature Biotechnology', colour: '#918F34', logo: './images/Nature-Biotechnology.png'},
	{name: 'Nature Catalysis', colour: '#2a63af', logo: './images/Nature-Catalysis.png'},
	{name: 'Nature Cell Biology', colour: '#065DA7', logo: './images/Nature-Cell-Biology.png'},
	{name: 'Nature Chemical Biology', colour: '#0080AF', logo: './images/Nature-Chemical-Biology.png'},
	{name: 'Nature Chemistry', colour: '#5C2483', logo: './images/Nature-Chemistry.png'},
	{name: 'Nature Climate Change', colour: '#0099BC', logo: './images/Nature-Climate-Change.png'},
	{name: 'Nature Communications', colour: '#507885', logo: './images/Nature-Communications.png'},
	{name: 'Nature Ecology & Evolution', colour: '#7c7640', logo: './images/Nature-Ecology-&-Evolution.png'},
	{name: 'Nature Electronics', colour: '#488a96', logo: './images/Nature-Electronics.png'},
	{name: 'Nature Energy', colour: '#ec6608', logo: './images/Nature-Energy.png'},
	{name: 'Nature Genetics', colour: '#4A6B53', logo: './images/Nature-Genetics.png'},
	{name: 'Nature Geoscience', colour: '#00663A', logo: './images/Nature-Geoscience.png'},
	{name: 'Nature Human Behaviour', colour: '#00497D', logo: './images/Nature-Human-Behaviour.png'},
	{name: 'Nature Immunology', colour: '#006394', logo: './images/Nature-Immunology.png'},
	{name: 'Nature Materials', colour: '#B60F3C', logo: './images/Nature-Materials.png'},
	{name: 'Nature Medicine', colour: '#981711', logo: './images/Nature-Medicine.png'},
	{name: 'Nature Methods', colour: '#4b617f', logo: './images/Nature-Methods.png'},
	{name: 'Nature Microbiology', colour: '#814997', logo: './images/Nature-Microbiology.png'},
	{name: 'Nature Nanotechnology', colour: '#E4AB00', logo: './images/Nature-Nanotechnology.png'},
	{name: 'Nature Neuroscience', colour: '#006E89', logo: './images/Nature-Neuroscience.png'},
	{name: 'Nature Photonics', colour: '#0062AB', logo: './images/Nature-Photonics.png'},
	{name: 'Nature Physics', colour: '#393187', logo: './images/Nature-Physics.png'},
	{name: 'Nature Plants', colour: '#3c7815', logo: './images/Nature-Plants.png'},
	{name: 'Nature Protocols', colour: '#523480', logo: './images/Nature-Protocols.png'},
	{name: 'Nature Reviews Cancer', colour: '#0086A7', logo: './images/Nature-Reviews-Cancer.png'},
	{name: 'Nature Reviews Cardiology', colour: '#7F6684', logo: './images/Nature-Reviews-Cardiology.png'},
	{name: 'Nature Reviews Chemistry', colour: '#19675D', logo: './images/Nature-Reviews-Chemistry.png'},
	{name: 'Nature Reviews Clinical Oncology', colour: '#768BA6', logo: './images/Nature-Reviews-Clinical-Oncology.png'},
	{name: 'Nature Reviews Disease Primers', colour: '#71a029', logo: './images/Nature-Reviews-Disease-Primers.png'},
	{name: 'Nature Reviews Drug Discovery', colour: '#E87B1D', logo: './images/Nature-Reviews-Drug-Discovery.png'},
	{name: 'Nature Reviews Endocrinology', colour: '#84A1AF', logo: './images/Nature-Reviews-Endocrinology.png'},
	{name: 'Nature Reviews Gastroenterology & Hepatology', colour: '#B5797B', logo: './images/Nature-Reviews-Gastroenterology-&-Hepatology.png'},
	{name: 'Nature Reviews Genetics', colour: '#b92e2e', logo: './images/Nature-Reviews-Genetics.png'},
	{name: 'Nature Reviews Immunology', colour: '#684A94', logo: './images/Nature-Reviews-Immunology.png'},
	{name: 'Nature Reviews Materials', colour: '#009adf', logo: './images/Nature-Reviews-Materials.png'},
	{name: 'Nature Reviews Microbiology', colour: '#7B0031', logo: './images/Nature-Reviews-Microbiology.png'},
	{name: 'Nature Reviews Molecular Cell Biology', colour: '#004981', logo: './images/Nature-Reviews-Molecular-Cell-Biology.png'},
	{name: 'Nature Reviews Nephrology', colour: '#93A8C5', logo: './images/Nature-Reviews-Nephrology.png'},
	{name: 'Nature Reviews Neurology', colour: '#9E7885', logo: './images/Nature-Reviews-Neurology.png'},
	{name: 'Nature Reviews Neuroscience', colour: '#007D35', logo: './images/Nature-Reviews-Neuroscience.png'},
	{name: 'Nature Reviews Rheumatology', colour: '#C39387', logo: './images/Nature-Reviews-Rheumatology.png'},
	{name: 'Nature Reviews Urology', colour: '#6E9292', logo: './images/Nature-Reviews-Urology.png'},
	{name: 'Nature Structural & Molecular Biology', colour: '#3F1F71', logo: './images/Nature-Structural-&-Molecular-Biology.png'},
	{name: 'Nature Sustainability', colour: '#c83c1c', logo: './images/Nature-Sustainability.png'},
	{name: 'Naturejobs', colour: '#085878', logo: './images/Naturejobs.png'},
	{name: 'Scientific Data', colour: '#3598C2', logo: './images/Scientific-Data.png'},
	{name: 'Scientific Reports', colour: '#E30613', logo: './images/Scientific-Reports.png'},
];

module.exports = journals;